system:
  progress-bar: 'stick'
  progress-format: '&f%skill_tree% &7(%level%) &8: &f%progress_bar% &8[&e%exp_percentage%%&8]'
  max-exp-formula: '%level%*32+((%level%%3)*%level%)'
  exp-min: 3
  exp-max: 5
  additional-levelup-skillpoint: 3

sounds:
  levelup: ENTITY_PLAYER_LEVELUP-1-2

progress-bar:
  stick:
    size: 20
    symbol: '|'
    filled-prefix: '&a'
    unfilled-prefix: '&7'

player-data:
  max-skill-tree: 3